### ISSUE TITLE
--bootstrap-system-full does not initialise system contract

### ISSUE THREAD

**Issue by michaeljyeates** [AntelopeIO/DUNE#130]
Created a container using --start and then --bootstrap-system-full

```
antelopeio-dune --create-account test
assertion failure with message: system contract must first be initialized
```

Running --bootstrap-system after this fixes it so that the account can be created

**Comment by mikelik** [comment]
Related issue: https://github.com/AntelopeIO/DUNE/issues/112

This is fixed on main, but not yet released. The issue was that there wasn't any currency set up.
If you don't want to wait until newest DUNE is released just checkout latest code from git and run ./dune --bootstrap-system-full which will now set up some example "SYS" currency.
And now if you want to create a new account you need to assign it some RAM, so the command would be:
`dune --system-newaccount <ACCOUNT> eosio  EOS8C5BLCX2LrmcRLHMC8bN5mML4aFSHrZvyijzfLy48tiije6nTt 5KNitA34Usr2EVLQKtFrwAJVhyB2F3U7fDHEuP2ee2zZ16w7PeB  -- --stake-net "1 SYS" --stake-cpu "1 SYS" --buy-ram-bytes 3000`
