### ISSUE TITLE
DUNE binary name conflicts with ocaml-dune on Linux

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/DUNE#141]
As a user I would like to have an easy way of installing and using DUNE.

Currently our DUNE's main binary name is named `dune`.
Unfortunately on Ubuntu by default there is already preinstalled ocaml-dune with the same binary name.

Currently when installing *.deb or *.rpm package we are adding `antelopeio-dune` binary to `/usr/bin` because of this conflict.
If user wants to use our DUNE he has to modify the $PATH manually.

**Comment by ScottBailey** [comment]
oacml-dune exists for OSX as well.

**Comment by ScottBailey** [comment]
Also, all caps naming feels unfriendly for Linux.

**Comment by ScottBailey** [comment]
These names have been suggested:
- dne
- dun
- duno
- duneo
- duneos

**Comment by kj4ezj** [comment]
I asked ChatGPT for some new names for DUNE. Most names were corny, a bit on the nose, or otherwise sucked. It suggested "AnteCoat", and I figured if you dropped "ante" and just used "coat" then it could be a pretty cool name. It invokes the idea of the coat of an Antelope, or just a coat you wear. You could even make a backronym if you really wanna stay on-brand, like "Container Orchestration for Antelope Tooling".

**Comment by stephenpdeos** [comment]
I know we've gravitated away from x-eos, but how about Docker Utility for Node Extension Operating Suite (DUNEOS)?

**Comment by mikelik** [comment]
From @larryk85: `dunes`

`For the dune rename, I am currently leaning towards "dunes" it's still a valid work, it's short, it still is an environment for Antelope just plural.  And the acronym can become Docker Utilities for Node Execution and Subsystems`

**Comment by stephenpdeos** [comment]
Decision: will update name to DUNES

**Comment by stephenpdeos** [comment]
Scope:

- [ ] Update binary names
- [ ] Update repo name
- [ ] Update readme
- [ ] Update supporting docs

Out of scope:

- [ ] Source code

@nsjames this change is coming and we will likely need a complimentary issue for DevRel. Any questions?

**Comment by jolly-fellow** [comment]
It seems documents like this https://github.com/eosnetworkfoundation/docs/blob/main/docs/20_smart-contracts/10_getting-started/10_dune-guide.md in other repositories should be updated too.

**Comment by ScottBailey** [comment]
> Out of scope:
> 
> * [ ]  Source code
> 
> Open questions
> 
> * [ ]  What about chocolatey?


I think we should revisit the issue of updating the source and file names. A global search and replace is probably easier now than it will ever be.

For example, my first review step could be ensuring that both the following commands return empty:

```sh
find | rg -i dune | rg -iv dunes
rg -i dune | rg -iv dunes
```

I think doing it all at once, reviewing it all at once, and TESTING it all at once instead of drawing it out might be a better approach.

**Comment by jolly-fellow** [comment]
It was agreed by the team in https://github.com/AntelopeIO/DUNE/pull/165 to rename everything at one time.

**Comment by ScottBailey** [comment]
@jolly-fellow sorry, my grep wasn't as good as it should have been, this is better:
```
find | rg -i dune  | rg -i dune[^s]
rg -i dune  | rg -i dune[^s]
```

**Comment by jolly-fellow** [comment]
Added a PR #179 which resolves this issue.
